# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0f6164a68a685fe9a48c798454dae141ae9fd25e8ec4d0facf30220715a4b1908a63b655624b06f13dc208d853f9ceb292685d07cfd276d1d4f8e03b6c367ba

test:
  secret_key_base: 97a66cdd20f167b08af4001518a8b9d832d12225417bfe4080c330722a77c246f1450d0892c9ac8df29e4c5ed87911b81ea9ba9c60bd3161421fd96cdbcb44b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
